on:
  push:
jobs:
  echo_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Echo the string
        uses: ./.github/actions/echoString@538ae48f9422a806257cfafde60884558c9829a4
        with:
          message: "This is the string to echo"

  echo_job_2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Echo the string again
        uses: ./.github/actions/echoString
        with:
          message: "This is the string to echo again"

  phpunit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - name: Install Composer dependencies (if composer.json exists)
        run: |
          if [ -f composer.json ]; then
            composer install --no-interaction --prefer-dist --optimize-autoloader;
          fi
      - name: Run PHPUnit
        run: |
          if [ -f ./vendor/bin/phpunit ]; then
            ./vendor/bin/phpunit;
          else
            phpunit;
          fi
